spring:
  data:
    redis:
      host: 127.0.0.1
      #      username: adad
      #      password: ada
      port: 6379
      database: 0
      timeout: 10000
      connect-timeout: 20000
      client-type: lettuce
      lettuce:
        pool:
          enabled: true
          max-idle: 8
          min-idle: 0
          max-active: 20
          max-wait: 20000
  datasource:
    url: jdbc:mysql://localhost:3306/file_server?useSSL=false&serverTimezone=Asia/Shanghai
    username: file_server
    password: file_server
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: MyHikariCP
  task:
    execution:
      pool:
        max-size: 16
        queue-capacity: 100
        keep-alive: 60s
        core-size: 8
mybatis:
  type-aliases-package: com.example.file_server.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  async-count: true
#logging:
#  level:
#    org:
#      mybatis: DEBUG
#      apache:
#        ibatis: DEBUG